name: OnPushNewVersion

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout st-launcher
        uses: actions/checkout@v2
        with:
          repository: impleotv/st-launcher
          token: ${{ secrets.TOKEN }}
          path: ./st-launcher          

      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}

      - name: Setup NodeJs 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./st-launcher
        
      - name: Build
        run: npm run pkgLinux
        working-directory: ./st-launcher

      - name: List files in the repository
        run: |
          tree -L 2 ${{ github.workspace }}

      - name: Create release    
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./st-launcher/st-launcher.run, ./st-launcher/CHANGELOG.md, ./st-launcher/README.md"       
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Setup NodeJs 16.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16.x'
      # - name: Cache dependencies and build outputs to improve workflow execution time.
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      # - name: Install dependencies
      #   run: npm install
      # - name: Set env
      #   run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # - name: Test
      #   run: |
      #     echo $RELEASE_VERSION
      #     echo ${{ env.RELEASE_VERSION }}
      # - name: Generate README file
      #   run: node index.js ${{env.RELEASE_VERSION }}


