name: OnPushNewVersion

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
  
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout st-launcher
        uses: actions/checkout@v3
        with:
          repository: impleotv/st-launcher
          token: ${{ secrets.TOKEN }}
          path: ./st-launcher          
      


      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}
