name: OnPushNewVersion

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
  
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout st-launcher
        uses: actions/checkout@v3
        with:
          repository: impleotv/st-launcher
          token: ${{ secrets.TOKEN }}
          path: ./st-launcher          
      
      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}


      - name: Setup NodeJs 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./st-launcher

      - name: Build
        run: npm run pkgLinux
        working-directory: ./st-launcher

      - name: List files in the repository
        run: |
          tree -L 2 ${{ github.workspace }}

      - name: Create release    
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./st-launcher/st-launcher.run, ./st-launcher/CHANGELOG.md, ./st-launcher/README.md"       
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install    
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: List files in the repository
        run: |
          tree -L 2 ${{ github.workspace }}

      - name: Print README.md
        run: |
          cat README.md

      - name: Generate README file
        run: node index.js ${{env.RELEASE_VERSION }}   

      - name: List files in the repository
        run: |
          tree -L 2 ${{ github.workspace }}

      - name: Clean up
        run: |
          rm -rf ./st-launcher
      - name: Print README.md
        run: |
          cat README.md
      # - name: Commit and Push new README.md to the repository
      #   uses: mikeal/publish-to-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updated README.md'
          add: 'README.md'